version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "30009:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=rootroot
    restart: always
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    restart: always
volumes:
  miniflux-db:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '/mnt/stick1/miniflux'

