version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: kunde21/gitea-arm
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30008:3000"
      - "6345:22"

volumes:
    gitea_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/data'
