version: '3'
services:
    jellyfin:
        image: jellyfin/jellyfin
        ports:
            - "30006:8096"
            - "8801:8920"
            - "8802:1900"
            - "8803:7359"
        volumes:
            - ./config:/config
            - ./cache:/cache
            - /mnt/vault2/media-lib/:/media
        restart: always
