---
- name: Ensure dotfiles
  ansible.builtin.import_playbook: dotfiles.yml
  when: hostvars[inventory_hostname]["ran_playbook_dotfiles"] is undefined

- name: Ensure shrc
  ansible.builtin.import_playbook: shrc.yml
  when: hostvars[inventory_hostname]["ran_playbook_shrc"] is undefined

- name: Ensure shell utils
  ansible.builtin.import_playbook: shell_utils.yml
  when: hostvars[inventory_hostname]["ran_playbook_shell_utils"] is undefined

- name: bash
  hosts: vm

  tasks:
  - name: Ensure bash
    become: true
    become_user: root
    apt:
      name: bash
      state: latest
  - name: Copy bashrc
    ansible.builtin.copy:
      src: /dotfiles/files/bash/.bashrc
      dest: ~/.bashrc
      remote_src: true
  - name: Set done variable
    ansible.builtin.set_fact:
      ran_playbook_bash: true
