---
- name: neovim install
  hosts: vm

  tasks:
  - name: Ensure offical neovim package is not installed
    become: true
    become_user: root
    apt:
      name: neovim
      state: absent
  - name: Check if neovim is installed
    stat:
      path: /usr/bin/nvim
    register: installed_nvim
  - name: Create nvim dir if it doesn't exist
    become: true
    become_user: root
    ansible.builtin.file:
      path: /tmp/nvim
      state: directory
      owner: debian
    when: not installed_nvim.stat.exists
  - name: Download nvim
    ansible.builtin.unarchive:
      src: https://github.com/neovim/neovim/releases/download/v0.6.1/nvim-linux64.tar.gz
      dest: /tmp/nvim
      remote_src: yes
    when: not installed_nvim.stat.exists
  - name: Install nvim
    become: true
    become_user: root
    ansible.builtin.copy:
      src: /tmp/nvim/nvim-linux64/bin/nvim
      dest: /usr/bin/nvim
      remote_src: yes
      mode: '701'
    when: not installed_nvim.stat.exists
  - name: Remove nvim dir
    become: true
    become_user: root
    ansible.builtin.file:
      path: /tmp/nvim
      state: absent
    when: not installed_nvim.stat.exists

- name: Ensure dotfiles
  ansible.builtin.import_playbook: dotfiles.yml

- name: neovim config
  hosts: vm

  tasks:
  - name: Create nvim config dirs if it doesn't exist
    ansible.builtin.file:
      path: "{{ item.dir }}"
      state: directory
      owner: debian
    loop:
      - { dir: "~/.local/share/nvim/site/pack/packer/start/" }
      - { dir: "~/.config/nvim/" }
      - { dir: "~/.config/nvim/lua/" }
      - { dir: "~/.config/nvim/ftplugin/" }
      - { dir: "~/.config/nvim/after/" }
      - { dir: "~/.config/nvim/after/syntax/" }
      - { dir: "~/.config/nvim/after/queries/" }
      - { dir: "~/.config/nvim/after/queries/markdown/" }
      - { dir: "~/.config/nvim/after/queries/lua/" }
  - name: neovim config files
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: true
    loop:
      - { src: "/dotfiles/files/nvim/init.lua", dest: "~/.config/nvim/init.lua" }
      - { src: "/dotfiles/files/nvim/lua/plugins.lua", dest: "~/.config/nvim/lua/plugins.lua" }
      - { src: "/dotfiles/files/nvim/lua/plugin-config.lua", dest: "~/.config/nvim/lua/plugin-config.lua" }
      - { src: "/dotfiles/files/nvim/lua/functions.lua", dest: "~/.config/nvim/lua/functions.lua" }
      - { src: "/dotfiles/files/nvim/lua/binds.lua", dest: "~/.config/nvim/lua/binds.lua" }
      - { src: "/dotfiles/files/nvim/lua/opts.lua", dest: "~/.config/nvim/lua/opts.lua" }
      - { src: "/dotfiles/files/nvim/lua/compile.lua", dest: "~/.config/nvim/lua/compile.lua" }
      - { src: "/dotfiles/files/nvim/lua/statusline-config.lua", dest: "~/.config/nvim/lua/statusline-config.lua" }
      - { src: "/dotfiles/files/nvim/ftplugin/c.lua", dest: "~/.config/nvim/ftplugin/c.lua" }
      - { src: "/dotfiles/files/nvim/ftplugin/cpp.lua", dest: "~/.config/nvim/ftplugin/cpp.lua" }
      - { src: "/dotfiles/files/nvim/ftplugin/make.lua", dest: "~/.config/nvim/ftplugin/make.lua" }
      - { src: "/dotfiles/files/nvim/ftplugin/markdown.vim", dest: "~/.config/nvim/ftplugin/markdown.vim" }
      - { src: "/dotfiles/files/nvim/ftplugin/tex.vim", dest: "~/.config/nvim/ftplugin/tex.vim" }
      - { src: "/dotfiles/files/nvim/ftplugin/norg.vim", dest: "~/.config/nvim/ftplugin/norg.vim" }
      - { src: "/dotfiles/files/nvim/after/syntax/markdown.vim", dest: "~/.config/nvim/after/syntax/markdown.vim" }
      - { src: "/dotfiles/files/nvim/after/queries/markdown/highlights.scm", dest: "~/.config/nvim/after/queries/markdown/highlights.scm" }
      - { src: "/dotfiles/files/nvim/after/queries/lua/textobjects.scm", dest: "~/.config/nvim/after/queries/lua/textobjects.scm" }
  - name: Clone packer repo
    ansible.builtin.git:
      repo: 'https://github.com/wbthomason/packer.nvim'
      dest: '~/.local/share/nvim/site/pack/packer/start/packer.nvim'
