version: '3.2'

volumes:
    nextcloud:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/nextcloud'
    db:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/db'

services:
    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
    app:
        image: nextcloud
        ports:
            - 8663:80
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            - MYSQL_HOST=db
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        restart: always
